server:
  port: ${CUSTOM.SERVER.PORT:9080}

resilience4j:
  circuitbreaker:
    configs:
      product-service-cb:
        slidingWindowSize: 12
        failureRateThreshold: 48
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 8
        slowCallRateThreshold: 58
        slowCallDurationThreshold: 500ms
        automaticTransitionFromOpenToHalfOpenEnabled: true
    instances:
      mitocode-product: 
        base-config: product-service-cb

# Spring Cloud Gateway Routes
spring:
  cloud:
    gateway:
      routes:

        - id: product-service-route
          uri: lb://product-service #http://service-1.com, http://service-2.com
          predicates:
            - Path=/api/product-service/**
          filters:
            - StripPrefix=2
            - AddRequestParameter=flag,true
            - name: CircuitBreaker
              args:
                name: mitocode-product
                statusCodes: 400,401,403,500,503
                fallbackUri: forward:/api/user-service/api/mitocode/user

        - id: user-service-route
          uri: lb://user-service
          predicates:
            - Path=/api/user-service/**
          filters:
            - StripPrefix=2
            #- name: CustomFilter
            #  args:
            #    headerKey: MitocodeKey
            #    headerValue: MitocodeValue
            - UserServiceFilter=MitocodeKey,MitocodeValue


  # Strangler Configuration

         # Service AS-IS Configuration -9023
        - id: product-query-service-route
          uri: lb://product-query-service
          predicates:
            - Path=/api/product-query-service/**
            - Weight=product, 90
          filters:
            - StripPrefix=2

         # Service TOB-BE Configuration - 9222
        - id: product-query-service-tobe-route
          uri: lb://product-query-service-tobe
          predicates:
            - Path=/api/product-query-service/**
            - Weight=product, 10
          filters:
            - StripPrefix=2

mitocode:
  security:
    key: cb5a5e83a031e8bdbee887001e4dcd202d5bff8402921506c489ed633be3460e