server:
  port: ${CUSTOM.SERVER.PORT:3001}

### Actuator info (/actuator/info)
info:
  app:
    name: Order  Service Microservice
    description: Microservicio para la gestión de las órdenes
    version: 1.0

### Mongo database configuration
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: mitocode
      uri: ${MONGODB.CONNECTION.URL:mongodb://mitocode:mitocode@localhost:27017}
      authentication-database: admin

management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /actuator
  info:
    env:
      enabled: true